---
- name: Update packages
  become: true
  apt:
    update_cache: yes

- name: Install npm and node
  become: true
  apt:
    name:
      - npm
      - nodejs
    state: latest
    update_cache: yes

- name: Install PM2 Globally
  npm:
    name: pm2
    global: yes