#alert manager
global:
 resolve_timeout: 1m
 slack_api_url: 'https://hooks.slack.com/services/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'
 
route:
 group_by: [Alertname]
 receiver: 'slack-notifications'
 
receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#monitoring_infra_alerts'
    send_resolved: true

route:
  group_by: [Alertname]
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: n.elkharbash@gmail.com
    from: nabkh94@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: nabkh94@gmail.com
    auth_identity: nabkh94@gmail.com
    auth_password: aqszebkpagwkmhmb