#prometheus.yml file

global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

rule_files:
  - /etc/prometheus/rules.yml
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093
        - ec2-54-86-201-129.compute-1.amazonaws.com:9093
scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['ec2-54-86-201-129.compute-1.amazonaws.com:9100']